### ISSUE TITLE
Opening fbx file results in OpenGLException: Cannot use offsets when Array Buffer Object is disabled

### ISSUE THREAD

**Issue by mistakenot** [ASneakyFox/libgdx-fbxconv-gui#1]
Hi,

Don't suppose you might of seen this before; fresh install of the tool, loads up fine, set the fbx location and go to browse for the fbx file, just a simple cube. As soon as I click on the cube in the explorer, this exception is thrown in the console.

Exception in thread "AWT-EventQueue-0" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Array Buffer Object is disabled
    at org.lwjgl.opengl.GLChecks.ensureArrayVBOenabled(GLChecks.java:93)
    at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:892)
    at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glVertexAttribPointer(LwjglGL20.java:746)
    at com.badlogic.gdx.graphics.glutils.ShaderProgram.setVertexAttribute(ShaderProgram.java:735)
    at com.badlogic.gdx.graphics.glutils.VertexBufferObject.bind(VertexBufferObject.java:182)
    at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:424)
... ... ...

I think it is happening when it initially tries to load the file for preview. Thanks for any advice you can offer.

**Comment by ASneakyFox** [comment]
Hmm, a couple questions- 

first of all what operating system are you on? Secondly, does this happen with any fbx file or a specific one? if its a specific file could you send me the file? also what program did you use to create the fbx file?

**Comment by mistakenot** [comment]
It's happened with both fbx files I've tried. I've attached the most recent. Please note that GitHub said it doesn't support .fbx files, so I added .jpg onto the end to get it to upload.

OS is Ubuntu 14.04. Program is Blender 2.69. Running Java 8. FBX file is bare bones cube exporting nothing but the mesh.

Might be related; when I navigate to the location of the fbx-conv-lin64 file in the explorer, it doesn't find the file. The folder is shown as empty. I typed in the name manually and clicked Ok and it seemed to accept it.

![untitled fbx](https://cloud.githubusercontent.com/assets/7852099/6065781/f7ffc590-ad5f-11e4-8e4c-fa416577f6cc.jpg)

**Comment by mistakenot** [comment]
Don't know if this adds anything useful, but here's the full trace:

com.badlogic.gdx.utils.SerializationException: Error parsing file: /home/charlie/libgdx/libgdx-fbxconv-gui/libgdx-model-viewer.temp.g3dj
    at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
    at com.badlogic.gdx.graphics.g3d.loader.G3dModelLoader.parseModel(G3dModelLoader.java:65)
    at com.badlogic.gdx.graphics.g3d.loader.G3dModelLoader.loadModelData(G3dModelLoader.java:61)
    at com.badlogic.gdx.assets.loaders.ModelLoader.loadModel(ModelLoader.java:53)
    at com.badlogic.gdx.assets.loaders.ModelLoader.loadModel(ModelLoader.java:69)
    at asf.modelpreview.ModelPreviewApp.previewFile(ModelPreviewApp.java:116)
    at asf.modelpreview.desktop.DesktopLauncher$14$2.run(DesktopLauncher.java:461)
    at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.render(LwjglAWTCanvas.java:250)
    at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas$1.paintGL(LwjglAWTCanvas.java:95)
    at org.lwjgl.opengl.AWTGLCanvas.paint(AWTGLCanvas.java:339)
    at org.lwjgl.opengl.AWTGLCanvas.update(AWTGLCanvas.java:368)
    at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
    at sun.awt.X11.XRepaintArea.updateComponent(XRepaintArea.java:60)
    at sun.awt.RepaintArea.paint(RepaintArea.java:232)
    at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
    at java.awt.Component.dispatchEventImpl(Component.java:4959)
    at java.awt.Component.dispatchEvent(Component.java:4705)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error reading file: /home/charlie/libgdx/libgdx-fbxconv-gui/libgdx-model-viewer.temp.g3dj (Absolute)
    at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:144)
    at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:163)
    at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
    ... 34 more
Caused by: java.io.FileNotFoundException: /home/charlie/libgdx/libgdx-fbxconv-gui/libgdx-model-viewer.temp.g3dj (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:131)
    at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:140)
    ... 36 more
Exception in thread "AWT-EventQueue-0" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Array Buffer Object is disabled
    at org.lwjgl.opengl.GLChecks.ensureArrayVBOenabled(GLChecks.java:93)
    at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:892)
    at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glVertexAttribPointer(LwjglGL20.java:746)
    at com.badlogic.gdx.graphics.glutils.ShaderProgram.setVertexAttribute(ShaderProgram.java:735)
    at com.badlogic.gdx.graphics.glutils.VertexBufferObject.bind(VertexBufferObject.java:182)
    at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:424)
    at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.render(BaseShader.java:246)
    at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.render(BaseShader.java:237)
    at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.render(DefaultShader.java:627)
    at com.badlogic.gdx.graphics.g3d.ModelBatch.flush(ModelBatch.java:213)
    at com.badlogic.gdx.graphics.g3d.ModelBatch.end(ModelBatch.java:224)
    at asf.modelpreview.ModelPreviewApp.render(ModelPreviewApp.java:195)
    at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.render(LwjglAWTCanvas.java:260)
    at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas$1.paintGL(LwjglAWTCanvas.java:95)
    at org.lwjgl.opengl.AWTGLCanvas.paint(AWTGLCanvas.java:339)
    at org.lwjgl.opengl.AWTGLCanvas.update(AWTGLCanvas.java:368)
    at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
    at sun.awt.X11.XRepaintArea.updateComponent(XRepaintArea.java:60)
    at sun.awt.RepaintArea.paint(RepaintArea.java:232)
    at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
    at java.awt.Component.dispatchEventImpl(Component.java:4959)
    at java.awt.Component.dispatchEvent(Component.java:4705)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mistakenot** [comment]
Have just resolved this. I didn't have two of the binarys for fbx in the right location (libfbxskd.dylib and .so). Moved them to /usr/lib/ and now the file is loading.

Thanks.

**Comment by ASneakyFox** [comment]
ah good to know thanks!

also i didnt realize fbx-conv-lin64 wasnt showing up properly in the explorer, ill fix that in the next update. if i can figure out a way to check for it programmaticaly i might see if i can throw in a warning to advice the user that the library files arent int he right folder (on linux and mac they have to be in /usr/lib or something, but on windows they can stay in the same directory). I'm sure other people will run in to the same thing as its not obvious that you need to add those files to to /usr/lib

**Comment by mistakenot** [comment]
Yeah, to be fair if I had set up fbx properly in the first place it wouldn't of happened! But I suppose a warning for first time users like myself would be handy. Great tool anyway.

**Comment by ASneakyFox** [comment]
quick question for you: after you put the .so and .dylib files in /usr/lib, are you now able to see fbx-conv-lin64 from the file chooser in the program?

**Comment by mistakenot** [comment]
Yep, moving the files resolved this issue as well.
